### ISSUE TITLE
Windows compilation

### ISSUE THREAD

**Issue by ggnkua** [christianparpart/contour#104]
Hi,

I decided to try out the terminal so I set out to build it on Windows, following your instructions. Here's some of my findings.

- CMake by default adds a x64-Debug target. On the other hand vcpkg by default builds and installs x86 targets. I fixed this by typing ```set VCPKG_DEFAULT_TRIPLET=x64-windows``` in a console and er-running vcpkg to rebuild all libraries. In retrospect I'm not sure if this could be fixed by adding a x86 target but I didn't want to introduce too many unknowns into the build since there were a load of weird CMake errors as you'll see below.

- I had some non-trivial CMake issues. The main cause is that all the test targets require pkg-config which is not available on Windows. So I bypassed this by deselecting the following bools: ```CATCH_BUILD_TESTING```, ```CONTOUR_TESTING```, ```CRISPY_TESTING```, ```BUILD_TESTING```, ```LIBTERMINAL_TESTING```. I'm not sure what can be done to enable tests but I guess it's not critical right now!

- Finally while building I noticed that you use a c++20 keyword, ```not```, I changed this to ```!``` and the build finished successfully. Of course I noticed that you fixed that in your non-master branch but I'm just stating it here anyway :).

That's all for now, it'd probably be a good idea if you updated your readme with some of the things above in order to save people's time!

Looking forward to see how this project turns out!
George

**Comment by ggnkua** [comment]
Forgot to add: first time vcpkg users should run ```vcpkg integrate install``` as an administrator in order to enable VS to use the compiled modules on its own!

**Comment by christianparpart** [comment]
Hey @ggnkua.

Many thanks for trying it out. With regards Windows & OS/X I will make sure it all safely runs and compiles as soon as I am finished on the current task (that is: finishing off emoji support).

I am generally developing on the `wip` branch (including commit squashing) and whenever I feel "safe", then I'm merging back to master, so that one should - ideally - always work.

Once I'm pushing out a release, I'll also attempt to create automated builds via CI for all 3 platforms. Please bare in mind, I'm (for now) the only contributor, but I am very happy to see some broader interest.

I will integrate your findings as soon as possible, many thanks!
Christian.

**Comment by christianparpart** [comment]
Once think I'd like to mention - on windows platform `fontconfig` isn't used, that is, the windows Font loading is hard coded. I need to address that (or see if fontconfig finally works on windows, it didn't back in time I tried it)

**Comment by ggnkua** [comment]
Hi Christian,

By all means don't feel any pressure from me! I see that the project is in its infancy but shows good potential!

I did have some crashes when running the binary, especially when resizing/fullscreening the window but I didn't want to mention them since I compiled the master branch which is behind latest. So it felt a bit pointless :).

George

**Comment by christianparpart** [comment]
Hey.
I am mainly working from Linux, because VT sequences debugging made me
crazy on Windows, because ConPTY and related new windows technologies are
all new too.
I can recommend trying it on Linux in case you have one. If not, well yeah.
I want this project to become my lifetime software project, i.e. it won't
go away easily. Many thanks for your support.

Christian.

**Comment by christianparpart** [comment]
Update: GithubActions for Windows CI has been revived and are successfully building again. Let's see how I now can address the above topics.

**Comment by csdvrx** [comment]
@ggnkua did you submit the cmake fixes?

The previous crash report on window resizing is very encouraging - it means contour should at least start.

But has it been tested at all on windows besides that?

@christianparpart  I'll be happy to at least test it your latest further (DCS sequences, Sixel etc.) if you have a x64 binary somewhere! I use msys2/mingw64 as my daily driver.

**Comment by ggnkua** [comment]
Hi @csdvrx,

It's been a while since I tried building it but I'm sure @christianparpart has addressed all the issues I describe above. I remember I could grab the latest master and build it without changes.

Also, if you go to the [releases section](https://github.com/christianparpart/contour/releases) of this repo you'll find pre-built Windows binaries.

Anyway, I guess we can close this issue now.

**Comment by christianparpart** [comment]
Hey guys, many thanks for your continued interest. I kept this ticket open as reminder for myself.

Feature wise there won't be added more until release. I am only addressing code quality and bugs. Windows lags behind and I want to make sure it works sufficiently on windows to before releasing .

While sixel works out of the box on Linux and OSX, for windows i can only support what ConPTY supports, I will be adding WinPTY support later.
