### ISSUE TITLE
Yellowish lines between characters

### ISSUE THREAD

**Issue by denniske** [christianparpart/contour#174]
## Description

There are yellowish lines between characters:

![image](https://user-images.githubusercontent.com/1076211/109153344-160ca480-776d-11eb-9a3e-de8fcccc387a.png)

## Environment

- Contour Version or Git commit hash: 0.1.1
- Operating System (name / distribution / version): Windows 10 20H2
- Contour configuration:
- TERM environment variable:
- Compiler version:

## Steps to Reproduce

Just downloaded the zip file for windows and started it.

**Comment by whisperity** [comment]
I have rendering issues with the release 0.1.1 on Linux, too.
But I think that issue is fixed, just a new full release wasn't made since. However, the CI was reworked to produce downloadable packages for normal commits too. What happens if you download the latest master Windows image from here: https://github.com/christianparpart/contour/actions/runs/599315367 ?

**Comment by denniske** [comment]
@whisperity I downloaded and installed that version. But when I start it, no window opens. And I see in task manager that Microsoft Compatibility Telemetry is using some CPU resources.

**Comment by christianparpart** [comment]
Hey @denniske, many thanks.

This specific issue is fixed on master. However, before you blindingly try out a new snapshot build, I am currently rewriting the font rendering especially to improve windows font rendering (and font fallback) support. This isn't finished yet. But that's what the next release is mainly about. Heads up. :-)
