### ISSUE TITLE
[Question] Is Vulkan support planned?

### ISSUE THREAD

**Issue by quadroli** [christianparpart/contour#228]
Just curious, considering that you started this project recently, did you consider using Vulkan?

**Comment by christianparpart** [comment]
Hey @quadroli 

Yes this came up recently. My reason for using OpenGL is platform independence though.

Note, adding a new backend shouldn't be more than implementing one interface, ideally. 

To be implemented should be the interface [RenderTarget](https://github.com/christianparpart/contour/blob/master/src/terminal_renderer/RenderTarget.h).

The implementation for OpenGL can be found [here] (https://github.com/christianparpart/contour/blob/master/src/terminal_renderer/opengl/OpenGLRenderer.h).

I am currently not having the time to focus on that, especially since I would need to read a lot of Vulkan documentation first.

Such  Feature could however be easily implemented by a contributor because all it needs from you would be knowledge of Vulkan and some very basics of Qt (how to create the Vulkan window area / widget).

This would though be a good first issue. :-)

**Comment by quadroli** [comment]
I see, thank you for the prompt response and sorry for my slightly late one, haven't been on in a while

Since that's settled, would it be safe to close the issue now?
